# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4f4f1b39bdcc0b8cf5cfe78cba8740a76b92a31b69d628379fa92e7eb90ca6c622082218e5c4458d55624bc1d8124a6fa7de5a8df9fa8186c8addfad82c9faf

test:
  secret_key_base: a6bc88786d5b4d178791c6471e8e30f26ce005c7d80009e5998cc64a9b6397c7bbe8a9dbe88815e018e9987213184bc1d1320c63ace7e2ba2439bde97cdd2239

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
